language: generic
sudo: required
before_install:
  - sudo apt update
  - sudo apt install python3-dev python3-pip python3-venv
install: 
  - python3 --version
  - pip3 install --upgrade pip
  - make setup
  - pip3 install --user --upgrade fontbakery

matrix:
  include:
    - dist: bionic
      env: TOX_ENV=static-ttf-tests
      script:
        - make static
        - fontbakery --version
        - fontbakery check-universal --loglevel WARN build/Valid/static/*.ttf
    - dist: bionic
      env: TOX_ENV=static-otf-tests
      script:
        - make static
        - fontbakery --version
        - fontbakery check-universal --loglevel WARN build/Valid/static/*.otf
    - dist: bionic
      env: TOX_ENV=variable-tests
      script:
        - make vf
        - fontbakery --version
        - fontbakery check-universal --loglevel WARN build/Valid/variable/*.ttf

notifications:
  email: false
