language: generic
sudo: required
before_install:
  - sudo apt update
  - sudo apt install python3-dev python3-pip python3-venv

matrix:
  include:
    - dist: bionic
      env: TOX_ENV=static-ttf-tests
      install: 
        - python3 --version
        - pip3 install --upgrade pip
        - make setup
        - pip3 install --user --upgrade fontbakery
      script:
        - make static
        - fontbakery --version
        - fontbakery check-universal build/Valid/static/*.ttf
    - dist: bionic
      env: TOX_ENV=static-otf-tests
      install: 
        - python3 --version
        - pip3 install --upgrade pip
        - make setup
        - pip3 install --user --upgrade fontbakery
      script:
        - make static
        - fontbakery --version
        - fontbakery check-universal build/Valid/static/*.otf
    - dist: bionic
      env: TOX_ENV=variable-tests
      install:
        - python3 --version
        - pip3 install --upgrade pip
        - make setup
        - pip3 install --user --upgrade fontbakery
      script:
        - make vf
        - fontbakery --version
        - fontbakery check-universal build/Valid/variable/*.ttf

notifications:
  email: false